const Products = [
  // Sofas
  {
    id: 1,
    name: "POUL CADOVIUS SOFA",
    category: "sofas",
    price: 17000,
    stock: 2,
    sku: "SOF-001",
    src: ["DSC_8444.jpg", "DSC_8448.jpg", "DSC_8440.jpg", "DSC_8442.jpg"],
    description:
      "This rare three-seater sofa was designed by Danish designer Poul Cadovius and produced by France & Son in Denmark during the 1960s. It exemplifies the refined balance of form and function that characterizes the best of Danish modern furniture. The sofa combines a striking rosewood frame with its original bouclé fabric upholstery, creating an engaging contrast between richly patterned wood and soft, textured fabric.",
  },
  {
    id: 2,
    name: "FOLKE JANSSONS SOFA",
    category: "sofas",
    price: 14500,
    stock: 1,
    sku: "SOF-002",
    src: ["DSC_7076.jpg", "DSC_7080.jpg", "DSC_7082.jpg"],
    description:
      "This is a rare and well-preserved example of the model “Tellus” sofa designed by Folke Jansson and produced by S. M. Wincrantz Möbelindustri in Sweden during the mid-20th century. The sofa demonstrates an elegant execution of Swedish mid-century modernism, combining sculptural form with precise upholstery work and fine detailing.",
  },
  {
    id: 3,
    name: "KHO LIANG IE SOFA",
    category: "sofas",
    price: 12500,
    stock: 3,
    sku: "SOF-003",
    src: ["DSC_6205.jpg", "DSC_6208.jpg", "DSC_6198.jpg", "DSC_6203.jpg"],
    description:
      "This sofa, model C683, was designed by Kho Liang Ie and produced by Artifort in the Netherlands in 1968. It is a prime example of late mid-century modern design, showcasing a minimalist yet sophisticated form that emphasizes both comfort and structural clarity.",
  },
  {
    id: 4,
    name: "ILLUM WIKKELSØ SOFA",
    category: "sofas",
    price: 14000,
    stock: 2,
    sku: "SOF-004",
    src: ["DSC_4233.jpg", "DSC_4246.jpg", "DSC_4249.jpg", "DSC_4251.jpg"],
    description:
      "The sofa model V12, designed by Illum Wikkelsø and produced by Holger Christensen in Denmark, is a refined and sculptural example of Danish mid-century modern design. This piece reflects Wikkelsø’s commitment to organic forms, comfort, and material harmony, and stands as a testament to the elegance and functionality that defined Scandinavian furniture in the 20th century.",
  },
  {
    id: 5,
    name: "HANS HARTL DAYBED",
    category: "sofas",
    price: 18500,
    stock: 1,
    sku: "SOF-005",
    src: ["DSC_3130.jpg", "DSC_3134.jpg", "DSC_3136.jpg", "DSC_3141.jpg"],
    description:
      "This rare daybed, designed by Hans Hartl and produced in 1954 by Herbert Anderssons Möbelverkstäder in Gärsnäs, Sweden, represents a sophisticated synthesis of modernist form and sculptural sensitivity. The piece showcases Hartl’s distinctive approach to ergonomic and spatial design, with a flowing, asymmetric profile that integrates both visual lightness and structural poise.",
  },
  {
    id: 6,
    name: "TOVE & EDVARD KINDT-LARSEN SOFA",
    category: "sofas",
    price: 15500,
    stock: 2,
    sku: "SOF-006",
    src: ["DSC_0806.jpg", "DSC_0808.jpg", "DSC_0813.jpg", "DSC_0814.jpg"],
    description:
      "This rare sofa, designed by Tove & Edvard Kindt-Larsen and produced by France & Son in Denmark during the 1950s, exemplifies the restrained elegance and functional clarity characteristic of mid-century Scandinavian design. The Kindt-Larsens, known for their refined architectural sensibility and attention to proportion, brought a balanced and humanistic approach to their furniture, evident in this thoughtfully executed piece.",
  },
  {
    id: 7,
    name: "FOLKE JANSSON SOFA",
    category: "sofas",
    price: 16000,
    stock: 1,
    sku: "SOF-007",
    src: ["DSC_8813.jpg", "DSC_8808.jpg", "DSC_8817.jpg"],
    description:
      "This very rare sofa, designed by Folke Jansson and produced in Sweden, is a distinctive example of Scandinavian mid-century modernism. The piece reflects Jansson’s sculptural approach to furniture design, with a form that balances geometric clarity and visual softness. The combination of materials—red leather and birch—results in a composition that is both visually bold and materially rich.",
  },
  {
    id: 8,
    name: "BRUNO MATHSSON DAYBED",
    category: "sofas",
    price: 20000,
    stock: 1,
    sku: "SOF-008",
    src: ["DSC_6612.jpg", "DSC_6615-2.jpg", "DSC_6615.jpg"],
    description:
      "The rare Berlin daybed, designed by Bruno Mathsson and produced by his father Karl Mathsson in Värnamo, Sweden, is a landmark piece in the canon of Scandinavian modern design. First introduced at the International Building Exhibition (Interbau) in Berlin in 1957, this model represents the synthesis of Mathsson’s ergonomic principles and his sensitivity to form, material, and proportion.",
  },
  {
    id: 9,
    name: "FRITZ HANSEN SOFA",
    category: "sofas",
    price: 13000,
    stock: 2,
    sku: "SOF-009",
    src: [
      "DSC_1459-scaled.jpg",
      "DSC_1455-scaled.jpg",
      "DSC_1461-scaled.jpg",
      "DSC_1464-scaled.jpg",
    ],
    description:
      "The model 1669a/4468 sofa, designed and produced by Fritz Hansen in Denmark in 1941, is a rare example of early Scandinavian mid-century design. It features a gently curved, fully upholstered frame with a tufted backrest, integrated armrests, and a deep seat, combining comfort with an elegant organic form. The sofa is supported by tapered solid beech legs that angle outward, providing both stability and a refined stance.",
  },
  {
    id: 10,
    name: "OLE WANSCHER SOFA",
    category: "sofas",
    price: 15500,
    stock: 2,
    sku: "SOF-010",
    src: [
      "DSC_8228-scaled.jpg",
      "DSC_8220-scaled.jpg",
      "DSC_8232-scaled.jpg",
      "DSC_8234-scaled.jpg",
    ],
    description:
      "This sofa, model 116, commonly known as the Senator, was designed by Ole Wanscher and produced by France & Son in Denmark in 1951. The frame is built from solid rosewood, notable for its rich, deep tones and pronounced grain patterns that highlight the natural beauty of the wood. The structural design is characterized by gently curved armrests, elegantly sculpted legs, and a subtly angled backrest, which together emphasize both ergonomic comfort and refined craftsmanship.",
  },
  {
    id: 11,
    name: "JOHANNES ANDERSEN SOFA",
    category: "sofas",
    price: 17000,
    stock: 1,
    sku: "SOF-011",
    src: [
      "DSC_5234-scaled.jpg",
      "DSC_5213-scaled.jpg",
      "DSC_5236-scaled.jpg",
      "DSC_5238-scaled.jpg",
    ],
    description:
      "This is a very rare sofa, model “Capri” designed by Johannes Andersen and produced by Trensum in Sweden during the 1960s. The design exemplifies Scandinavian mid-century modernism with a distinct sculptural form and an emphasis on luxurious materials and modernist elegance.",
  },
  {
    id: 12,
    name: "ILLUM WIKKELSØ SOFA",
    category: "sofas",
    price: 19000,
    stock: 1,
    sku: "SOF-012",
    src: [
      "DSC_0341.jpg",
      "DSC_0348.jpg",
      "DSC_0337.jpg",
      "DSC_0344.jpg",
      "DSC_0336.jpg",
    ],
    description:
      "Very rare sofa model Croissant designed by Illum Wikkelsø Produced by Holger Christiansen in Denmark Rosewood and light beige leather Excellent vintage condition, with minor signs of usage and patina 1950′s",
  },
  // Easy Chairs
  {
    id: 13,
    name: "PAUL LEIDERSDORFF EASY CHAIRS",
    category: "easy chairs",
    price: 9500,
    stock: 2,
    sku: "ECH-001",
    src: ["DSC_5998.jpg", "DSC_6000.jpg", "DSC_6008.jpg", "DSC_6015.jpg"],
    description:
      "This pair of easy chairs, model “Caravelle” was designed by Paul Leidersdorff in 1965 and produced by A. Leidersdorffsen A/S in Denmark. The chairs feature a frame combining industrial and organic materials, with a structural base in brushed aluminum and a backrest formed by slatted black-stained wood panels. ",
  },
  {
    id: 14,
    name: "IB MADSEN & ACTON SCHUBELL EASY CHAIRS",
    category: "easy chairs",
    price: 12000,
    stock: 1,
    sku: "ECH-002",
    src: ["DSC_5188.jpg", "DSC_5190.jpg", "DSC_5192.jpg", "DSC_5193.jpg"],
    description:
      "This rare pair of easy chairs was designed by Danish designers Ib Madsen and Acton Schubell and produced in Denmark during the 1950s. The chairs exhibit a masterful balance between organic shaping and structural elegance, hallmarks of Scandinavian mid-century modernism. Both chairs feature sculptural, dark-stained beech frames with a flowing profile characterized by softly curved armrests, subtly tapered legs, and gracefully arched seat supports. The craftsmanship of the joinery and the fluidity of the woodwork are consistent with high-quality Danish cabinetmaking of the period.",
  },
  {
    id: 15,
    name: "HANS EICHENBERGER EASY CHAIRS",
    category: "easy chairs",
    price: 10000,
    stock: 2,
    sku: "ECH-003",
    src: ["DSC_5102.jpg", "DSC_5110.jpg", "DSC_5111.jpg", "DSC_5115.jpg"],
    description:
      "This rare pair of easy chairs was designed by Hans Eichenberger and produced by Girsberger in Switzerland in 1962. The chairs exemplify the rationalist minimalism and engineering precision that characterize Swiss modernist design during the mid-20th century. Their form combines rigorous structural clarity with restrained material expression.",
  },
  {
    id: 16,
    name: "OTTO SCHULZ EASY CHAIRS",
    category: "easy chairs",
    price: 13500,
    stock: 1,
    sku: "ECH-004",
    src: ["DSC_4187.jpg", "DSC_4195.jpg", "DSC_4200.jpg"],
    description:
      "This very rare pair of easy chairs, designed by Otto Schulz and produced in the 1940s by Boet in Sweden, stands as a refined example of Swedish Art Deco design transitioning into early modernism. Schulz, known for his ability to blend bold form with comfort and craftsmanship, imbued these chairs with sculptural presence and a strong sense of materiality, making them both functional and visually captivating.",
  },
  {
    id: 17,
    name: "JIO MÖBLER LOUNGE CHAIR",
    category: "easy chairs",
    price: 8500,
    stock: 2,
    sku: "ECH-005",
    src: ["DSC_5566-scaled.jpg", "DSC_5570-scaled.jpg", "DSC_5582-scaled.jpg"],
    description:
      "This rare “Siesta” lounge chair with its matching ottoman was produced by JIO Möbler in Sweden during the 1960s and remains an exemplary piece of Swedish mid-century modernism. The design’s author is unrecorded, yet its combination of structural clarity and supremely comfortable form marks it as a thoughtfully conceived lounge ensemble. The chair’s sculptural oak frame, with its sharply tapering legs and angular side profiles, projects both visual lightness and architectural precision, while the ottoman mirrors these geometric lines to form a harmonious pair.",
  },
  {
    id: 18,
    name: "FOLKE OHLSSON EASY CHAIRS",
    category: "easy chairs",
    price: 9500,
    stock: 3,
    sku: "ECH-006",
    src: [
      "DSC_3589.jpg",
      "DSC_3585.jpg",
      "DSC_3591.jpg",
      "DSC_3593.jpg",
      "DSC_3603.jpg",
    ],
    description:
      "This rare pair of USA 75 easy chairs, designed by Folke Ohlsson and produced in 1963 by DUX in Sweden, represents a masterful blend of Scandinavian craftsmanship and international modernist aesthetics. The model is a hallmark of Ohlsson’s design philosophy—functionally elegant, material-rich, and subtly expressive—crafted during a time when Swedish furniture design was gaining widespread acclaim on the global stage.",
  },
  {
    id: 19,
    name: "IB KOFOD-LARSEN EASY CHAIR",
    category: "easy chairs",
    price: 14000,
    stock: 1,
    sku: "ECH-007",
    src: ["DSC_9405.jpg", "DSC_9408.jpg", "DSC_9409.jpg", "DSC_9416.jpg"],
    description:
      "This very rare easy chair and stool set, model U56, also known as the Elizabeth chair, was designed in 1956 by Ib Kofod-Larsen and produced by the distinguished Danish cabinetmaker Christensen & Larsen. A celebrated piece of mid-century Scandinavian design, the set is recognized not only for its refined aesthetics and comfort but also for its historical significance—the model gained its name after Queen Elizabeth II acquired a pair during a state visit to Denmark.",
  },
  {
    id: 20,
    name: "JAN EKSELIUS LOUNGE CHAIR",
    category: "easy chairs",
    price: 8000,
    stock: 2,
    sku: "ECH-008",
    src: ["DSC_2511.jpg", "DSC_2508.jpg", "DSC_2509.jpg", "DSC_2512.jpg"],
    description:
      "The rare Etcetera lounge chair, designed by Jan Ekselius and produced by JOC Möbel AB in Vetlanda, Sweden during the 1960s, is a celebrated icon of Scandinavian modernism that seamlessly merges sculptural form with functional innovation. Known for its distinctive flowing silhouette and ergonomic design, the Etcetera chair embodies the bold experimentation of 1960s design while remaining deeply rooted in the Scandinavian ethos of comfort, craftsmanship, and visual clarity.",
  },
  {
    id: 21,
    name: "SVEN IVAR DYSTHE EASY CHAIRS",
    category: "easy chairs",
    price: 9500,
    stock: 2,
    sku: "ECH-009",
    src: ["DSC_9852.jpg", "DSC_9844.jpg"],
    description:
      "This rare pair of easy chairs, designed by Sven Ivar Dysthe and produced by Dokka Møbler in Norway during the 1960s, exemplifies the sophisticated balance between industrial materials and traditional craftsmanship characteristic of Scandinavian modernism. The chairs feature a polished steel frame that provides structural clarity and a sense of architectural precision. Suspended within this frame are black leather seat and backrest panels, which contribute to a lightweight, almost floating appearance while maintaining comfort and support.",
  },
  {
    id: 22,
    name: "AKSEL BENDER MADSEN & EJNER LARSEN EASY CHAIRS",
    category: "easy chairs",
    price: 11000,
    stock: 1,
    sku: "ECH-010",
    src: [
      "DSC_4143-scaled.jpg",
      "DSC_4145-scaled.jpg",
      "DSC_4147-scaled.jpg",
      "DSC_4158-scaled.jpg",
    ],
    description:
      "This rare pair of easy chairs was designed by Aksel Bender Madsen and Ejner Larsen, produced by cabinetmaker Willy Beck in Denmark during the 1950s. The chairs exhibit a solid teak frame, notable for its elegantly curved armrests that reflect the refined woodworking skills characteristic of Danish craftsmanship in the mid-century period. The teak surfaces have aged with a rich patina, highlighting the wood’s natural grain and depth.",
  },
  // Chairs
  {
    id: 23,
    name: "IB KOFOD-LARSEN ARMCHAIR",
    category: "chairs",
    price: 7500,
    stock: 3,
    sku: "CHR-001",
    src: [
      "DSC_8687.jpg",
      "DSC_8690.jpg",
      "DSC_8693.jpg",
      "DSC_8697.jpg",
      "DSC_8707.jpg",
    ],
    description:
      "This very rare armchair, model Elizabeth, was designed by the distinguished Danish designer Ib Kofod-Larsen and produced by the Danish cabinetmaker Christensen & Larsen during the 1950s. Recognized for its exceptional craftsmanship and refined form, this model stands as one of Kofod-Larsen’s most celebrated and collectible creations within the canon of Scandinavian modernist design.",
  },
  {
    id: 24,
    name: "AXEL EINAR HJORTH DINING CHAIRS",
    category: "chairs",
    price: 21000,
    stock: 2,
    sku: "CHR-002",
    src: ["DSC_4057.jpg", "DSC_4054.jpg", "DSC_4068.jpg", "DSC_4079.jpg"],
    description:
      "This rare and exquisite set of Borgholm chairs—comprising two armchairs and four side chairs—was designed by Axel Einar Hjorth and produced by Bodafors in Sweden during the 1930s. The set is a definitive example of Swedish Grace, a style that emerged between classicism and modernism, characterized by its balance of architectural clarity, ornamentation, and superior craftsmanship.",
  },
  {
    id: 25,
    name: "JENS RISOM ARMCHAIRS",
    category: "chairs",
    price: 18000,
    stock: 2,
    sku: "CHR-003",
    src: [
      "DSC_3120.jpg",
      "DSC_3113.jpg",
      "DSC_3115-2.jpg",
      "DSC_3116.jpg",
      "DSC_3118.jpg",
    ],
    description:
      "This rare set of six armchairs, model Playboy / C140, was designed by Jens Risom in 1960 and produced by Risom Design in Denmark. Each chair exemplifies Risom’s capacity to balance sculptural elegance with functional rigor, resulting in a design that is both refined and enduring.",
  },
  {
    id: 26,
    name: "HANS WEGNER ARMCHAIRS",
    category: "chairs",
    price: 32000,
    stock: 1,
    sku: "CHR-004",
    src: ["DSC_1973.jpg", "DSC_1962.jpg", "DSC_1968.jpg", "DSC_1978.jpg"],
    description:
      "This rare set of twelve armchairs, model JH-507, was designed by Hans J. Wegner and produced by the esteemed Danish cabinetmaker Johannes Hansen in the 1950s. The chairs epitomize the refined craftsmanship and sculptural elegance that define Wegner’s contributions to mid-century Scandinavian design.",
  },
  {
    id: 27,
    name: "JØRGEN LUND & OLE LARSEN OFFICE CHAIR",
    category: "chairs",
    price: 7200,
    stock: 2,
    sku: "CHR-005",
    src: ["DSC_0222.jpg", "DSC_0232.jpg", "DSC_0238.jpg"],
    description:
      "This very rare office chair, model 932, was designed by Jørgen Lund and Ole Larsen and produced by Bo-Ex in Denmark during the 1960s. The chair features an organically curved shell upholstered in its original dark brown leather, which has developed a rich patina over time. The leather shows natural wear including creases, minor surface scratches, and some discoloration, all contributing to the chair’s authentic vintage character. The seat cushion remains intact with firm padding, ensuring continued comfort and usability.",
  },
  {
    id: 28,
    name: "HORST BRÜNING ARMCHAIRS",
    category: "chairs",
    price: 14000,
    stock: 2,
    sku: "CHR-006",
    src: ["DSC_3178-scaled.jpg", "DSC_3168-scaled.jpg", "DSC_3173-scaled.jpg"],
    description:
      "This rare set of four armchairs was designed by Horst Brüning and produced by Alfred Kill International in Germany in 1968. The chairs showcase a sophisticated blend of materials, featuring tubular stainless steel frames paired with seats upholstered in high-quality black leather. The leather has aged gracefully, developing a patina with natural wear that enhances the vintage character of the pieces.",
  },
  {
    id: 29,
    name: "HANS OLSEN ARMCHAIRS",
    category: "chairs",
    price: 12000,
    stock: 2,
    sku: "CHR-007",
    src: [
      "DSC_3652-scaled.jpg",
      "DSC_3635-scaled.jpg",
      "DSC_3643-scaled.jpg",
      "DSC_3649-scaled.jpg",
    ],
    description:
      "This rare set of armchairs, model 30, was designed by Hans Olsen and produced by CS Møbler in Denmark during the 1960s. Crafted from solid rosewood, the chairs showcase a deep, rich grain that highlights the sculptural elegance of the design. The gently curved backrest flows seamlessly into the armrests, creating a continuous, organic form that balances aesthetics with comfort.",
  },
  {
    id: 30,
    name: "FINN JUHL ARMCHAIRS",
    category: "chairs",
    price: 25000,
    stock: 1,
    sku: "CHR-008",
    src: [
      "DSC_2876-scaled.jpg",
      "DSC_2872-scaled.jpg",
      "DSC_2877-scaled.jpg",
      "DSC_2878-scaled.jpg",
      "DSC_2887-scaled.jpg",
    ],
    description:
      "This is a rare set of six armchairs, model FD 209, also known as the Diplomat chair, designed by Danish architect and designer Finn Juhl in the 1960s. The chairs were produced by Cado, which became known for high-end Danish furniture. The frames are constructed from solid teak, displaying a warm golden-brown tone and subtle figuring in the grain.",
  },
  // Storage
  {
    id: 31,
    name: "HENRY ROSENGREN HANSEN SIDEBOARD",
    category: "storage",
    price: 11500,
    stock: 2,
    sku: "STO-001",
    src: ["DSC_8613.jpg", "DSC_8610.jpg", "DSC_8615.jpg", "DSC_8617.jpg"],
    description:
      "This rare sideboard is designed by Henry Rosengren Hansen and produced by Brande Møbelindustri during the 1950s. Crafted in richly grained rosewood, the sideboard displays the refined minimalism and functional elegance characteristic of Danish modern design.",
  },
  {
    id: 32,
    name: "AXEL EINAR HJORTH CABINET",
    category: "storage",
    price: 18500,
    stock: 1,
    sku: "STO-002",
    src: ["DSC_7417.jpg", "DSC_7405.jpg", "DSC_7408.jpg"],
    description:
      "This cabinet, known as the “Metropolitan” model, was designed by Axel Einar Hjorth and produced by Albin Johansson in Sweden during the 1920s. It is a rare example of Swedish Grace, a style that emerged in the interwar period combining classical restraint with modern elegance. This particular version corresponds to the model exhibited at the Metropolitan Museum of Art in New York during the 1927 exhibition “Swedish Contemporary Decorative Arts” an event that marked the international recognition of Swedish design.",
  },
  {
    id: 33,
    name: "JOHAN HAGEN BOOKCASES",
    category: "storage",
    price: 9500,
    stock: 2,
    sku: "STO-003",
    src: ["DSC_5316.jpg", "DSC_5318.jpg", "DSC_5321.jpg", "DSC_5329.jpg"],
    description:
      "This is a pair of bookcases designed by Johan Hagen and crafted by cabinetmaker I. Christiansen in Denmark during the 1950s. Constructed entirely from rosewood, the bookcases exhibit the distinct visual richness and complexity associated with this tropical hardwood. The material is characterized by dark brown and black streaks interwoven with reddish and golden undertones, arranged in a vertical grain pattern on the back panels and horizontal alignment on the shelf surfaces. The craftsmanship emphasizes precision joinery and clean profiles, presenting a refined interpretation of Danish modernism.",
  },
  {
    id: 34,
    name: "OTTO SCHULZ CABINET",
    category: "storage",
    price: 13500,
    stock: 1,
    sku: "STO-004",
    src: ["DSC_1970.jpg", "DSC_1980.jpg", "DSC_1982.jpg", "DSC_1988.jpg"],
    description:
      "This very rare cabinet, designed by Otto Schulz and produced by Boet in Sweden, is a remarkable testament to early Scandinavian modernism, distinguished by its material experimentation, decorative restraint, and finely balanced proportions. It reflects Schulz’s distinctive aesthetic—at once forward-thinking and rooted in artisanal tradition—and offers an exemplary instance of his unique approach to furniture design during the mid-20th century.",
  },
  {
    id: 35,
    name: "CABINET",
    category: "storage",
    price: 8000,
    stock: 2,
    sku: "STO-005",
    src: [
      "DSC_1409.jpg",
      "DSC_1416.jpg",
      "DSC_1417.jpg",
      "DSC_1419.jpg",
      "DSC_1424.jpg",
    ],
    description:
      "This very rare Swedish cabinet, crafted from mahogany and elm root veneer, is a refined example of early to mid-20th-century Scandinavian craftsmanship. Though the designer remains unidentified, the cabinet clearly embodies the hallmarks of Swedish design from this period: geometric clarity, expert veneer work, and an emphasis on both functional structure and material richness.",
  },
  {
    id: 36,
    name: "KAI KRISTIANSEN BUREAU",
    category: "storage",
    price: 7200,
    stock: 3,
    sku: "STO-006",
    src: ["DSC_6994.jpg", "DSC_6996.jpg", "DSC_6997.jpg", "DSC_7000.jpg"],
    description:
      "This rare bureau or side table, model 394, designed by Kai Kristiansen and produced by Aksel Kjersgaard in Denmark, is a refined example of mid-century Danish design that balances function, proportion, and material richness. Created in the 1960s, the piece exemplifies Kristiansen’s distinct approach to form—elegant yet pragmatic, with a focus on clean lines and thoughtful detailing.",
  },
  {
    id: 37,
    name: "ESTRID ERICSON & JOSEF FRANK CHEST",
    category: "storage",
    price: 16500,
    stock: 1,
    sku: "STO-007",
    src: [
      "DSC_3322.jpg",
      "DSC_3324.jpg",
      "DSC_3326.jpg",
      "DSC_3329.jpg",
      "DSC_3331.jpg",
    ],
    description:
      "This exceptionally rare freestanding chest, designed by Estrid Ericson and Josef Frank for Svenskt Tenn in Sweden during the 1940s, exemplifies a distinctive fusion of decorative artistry and functional modern design. It serves as a key representation of Svenskt Tenn’s ethos under Ericson’s leadership and Frank’s visionary approach, which emphasized eclecticism, craftsmanship, and a global sensibility rooted in European and Asian traditions.",
  },
  {
    id: 38,
    name: "OVE FEUK BUREAU",
    category: "storage",
    price: 9000,
    stock: 2,
    sku: "STO-008",
    src: ["DSC_3307.jpg", "DSC_3305.jpg", "DSC_3308.jpg", "DSC_3311.jpg"],
    description:
      "This rare freestanding bureau, designed by Ove Feuk and produced by Nordiska Kompaniet in Sweden during the 1960s, is a refined example of Scandinavian modernism that balances material luxury with functional clarity. The bureau’s structure is composed of a solid wooden carcass, fully upholstered in black leather. The leather presents a subtly textured surface with natural tonal variation and a rich patina that has developed over time, underscoring the age, authenticity, and enduring quality of the piece.",
  },
  {
    id: 39,
    name: "SWEDISH GRACE CABINET",
    category: "storage",
    price: 11000,
    stock: 2,
    sku: "STO-009",
    src: ["DSC_2594.jpg", "DSC_2589.jpg", "DSC_2592.jpg"],
    description:
      "This rare Swedish Grace cabinet, produced in Sweden during the 1920s, is a distinguished example of one of Scandinavia’s most refined stylistic periods—a graceful synthesis of neoclassicism, Art Deco, and functionalist restraint. While the designer remains unknown, the craftsmanship and ornamental language clearly align with the principles of Swedish Grace, a movement that gained international acclaim for its harmonious balance of elegance and utility.",
  },
  {
    id: 40,
    name: "KURT ØSTERVIG BAR CABINET",
    category: "storage",
    price: 9500,
    stock: 2,
    sku: "STO-010",
    src: [
      "DSC_3252-scaled.jpg",
      "DSC_3254-scaled.jpg",
      "DSC_3257-scaled.jpg",
      "DSC_3261-scaled.jpg",
    ],
    description:
      "This rare bar cabinet was designed by Kurt Østervig and produced by K.P. Møbler in Denmark during the 1960s. It exemplifies Scandinavian modern design with its clean lines, functional layout, and high-quality craftsmanship.",
  },
  // Tables
  {
    id: 41,
    name: "SEVERIN HANSEN SIDE TABLE",
    category: "tables",
    price: 3900,
    stock: 4,
    sku: "TAB-001",
    src: ["DSC_9118.jpg", "DSC_9123.jpg", "DSC_9125.jpg"],
    description:
      "This side table was designed by Severin Hansen Jr. and produced by Haslev Møbelsnedkeri in Denmark during the height of Danish modernism in the mid-20th century. It represents a refined expression of minimalist design principles combined with high-quality cabinetmaking, characteristic of Hansen’s work and the ethos of the Danish furniture tradition.",
  },
  {
    id: 42,
    name: "AXEL EINAR HJORTH DINING TABLE",
    category: "tables",
    price: 17500,
    stock: 1,
    sku: "TAB-002",
    src: ["DSC_5602.jpg", "DSC_5606.jpg", "DSC_5608.jpg"],
    description:
      "This is a very rare dining table, model Värmdö, designed by Axel Einar Hjorth and produced by Nordiska Kompaniet (NK) in Sweden during the 1930s. The table belongs to Hjorth’s series of furniture created for Swedish summer houses, known as Sportstugemöbler, which combined rustic materials with early modernist forms. Unlike most examples of the Värmdö table that were produced entirely in pine, this particular piece features pine legs with an original oak tabletop, creating a subtle yet striking material contrast.",
  },
  {
    id: 43,
    name: "CARL MALMSTEN DESK",
    category: "tables",
    price: 6800,
    stock: 2,
    sku: "TAB-003",
    src: ["DSC_3356.jpg", "DSC_3351.jpg", "DSC_3354.jpg"],
    description:
      "This rare desk, designed by Carl Malmsten and produced by Nordiska Kompaniet in Sweden during the 1930s, is a refined example of Swedish Art Deco craftsmanship and design. Created during a period when Malmsten was transitioning from the ornamental influences of National Romanticism to a more modernist but still classically grounded idiom, the desk embodies a subtle balance of decorative detailing and structural clarity.",
  },
  {
    id: 44,
    name: "SVEN ENGSTRÖM & GUNNAR MYRSTRAND BEDSIDE TABLES",
    category: "tables",
    price: 4300,
    stock: 3,
    sku: "TAB-004",
    src: ["DSC_2319.jpg", "DSC_2324.jpg", "DSC_2325.jpg"],
    description:
      "This pair of bedside or side tables, model Casino, was designed by Swedish designers Sven Engström and Gunnar Myrstrand and produced by Tingströms in Sweden. Created during the peak of Scandinavian modernism, these tables are exemplary of the movement’s core principles: a dedication to functional clarity, an emphasis on natural materials, and a commitment to restrained elegance.",
  },
  {
    id: 45,
    name: "JACOB KJÆR ATTRIB. DESK",
    category: "tables",
    price: 7200,
    stock: 2,
    sku: "TAB-005",
    src: ["DSC_9454.jpg", "DSC_9448.jpg", "DSC_9449.jpg", "DSC_9450.jpg"],
    description:
      "This rare freestanding desk, attributed to Jacob Kjær and produced in Denmark, is an exemplary piece of mid-20th-century Danish design that combines refined materials with a restrained, architectural aesthetic. It reflects the principles central to Kjær’s work—clarity of form, high-quality craftsmanship, and an emphasis on both beauty and function.",
  },
  {
    id: 46,
    name: "POUL HUNDEVAD COFFEE TABLE",
    category: "tables",
    price: 5100,
    stock: 3,
    sku: "TAB-006",
    src: ["DSC_9647.jpg", "DSC_9649.jpg", "DSC_9653.jpg"],
    description:
      "This rare coffee table, model Guldhøj, was designed by Poul Hundevad and produced in Vamdrup, Denmark. Named after the Guldhøj burial mound in southern Jutland, from which the design draws inspiration, the table is an embodiment of Danish mid-century design that fuses functional simplicity with sculptural expression.",
  },
  {
    id: 47,
    name: "JOSEF FRANK COFFEE TABLE",
    category: "tables",
    price: 9000,
    stock: 2,
    sku: "TAB-007",
    src: ["DSC_9323.jpg", "DSC_9326.jpg", "DSC_9333.jpg"],
    description:
      "This rare coffee or side table was designed in 1934 by Josef Frank and produced by Svenskt Tenn in Sweden. It exemplifies Frank’s approach to furniture design, where restrained modernist form meets refined material sensibility. The table consists of a circular top made of natural stone—marble—resting on a mahogany frame. The marble is highly polished and reveals an intricate surface of organic veining and coloration, adding depth and visual interest to the otherwise minimal silhouette.",
  },
  {
    id: 48,
    name: "SVANTE SKOGH DINING TABLE",
    category: "tables",
    price: 12500,
    stock: 1,
    sku: "TAB-008",
    src: ["DSC_6371.jpg", "DSC_6372.jpg", "DSC_6374.jpg", "DSC_6377.jpg"],
    description:
      "The Cortina dining table, designed by Svante Skogh and produced by Seffle Möbelfabrik in 1958, stands as a distinguished example of Scandinavian modernism at its most refined. Marrying the functional clarity of mid-century design with luxurious materials and exceptional craftsmanship, this table encapsulates Skogh’s thoughtful design approach and his attention to proportion, detail, and materiality.",
  },
  // Light
  {
    id: 49,
    name: "CEILING LAMP",
    category: "light",
    price: 2100,
    stock: 5,
    sku: "LGT-001",
    src: ["DSC_7492.jpg", "DSC_7499.jpg", "DSC_7500.jpg"],
    description:
      "This rare ceiling lamp or flush mount was produced in Denmark during the mid-20th century and exemplifies the pared-down functionalist aesthetics of Scandinavian lighting design. The construction utilizes a combination of solid brass and opaline glass, materials favored for their durability, luminous quality, and ability to age attractively.",
  },
  {
    id: 50,
    name: "CARL-AXEL ACKING WALL LAMPS",
    category: "light",
    price: 3500,
    stock: 2,
    sku: "LGT-002",
    src: ["DSC_4978.jpg", "DSC_4979.jpg", "DSC_4984.jpg"],
    description:
      "This rare pair of wall lamps was designed by Swedish architect and designer Carl-Axel Acking and produced in Sweden during the 1960s. Exemplifying Scandinavian mid-century modernism, the lamps explore architectural geometry and light diffusion through a precise, sculptural arrangement of brass panels. Each lamp consists of a vertically stacked composition of parallel and perpendicular brass blades, forming a three-dimensional matrix that interacts with both light and shadow.",
  },
  {
    id: 51,
    name: "ROLF GRAAE WALL LAMPS",
    category: "light",
    price: 3200,
    stock: 2,
    sku: "LGT-003",
    src: ["DSC_4906.jpg", "DSC_4907.jpg", "DSC_4923.jpg", "DSC_4925.jpg"],
    description:
      "This rare set of decorative wall lamps was designed by Danish architect and designer Rolf Graae and produced by Tema in Denmark during the 1950s. The design is characterized by its geometric structure and sculptural presence, aligning with Graae’s architectural sensibility and attention to formal rhythm.",
  },
  {
    id: 52,
    name: "TORSTEN THORUP & CLAUS BONDERUP WALL LAMPS",
    category: "light",
    price: 3300,
    stock: 2,
    sku: "LGT-004",
    src: ["DSC_4891.jpg", "DSC_4895.jpg", "DSC_4896.jpg", "DSC_4901.jpg"],
    description:
      "This rare set of wall-mounted lamps, model Quarto, was designed by Torsten Thorup and Claus Bonderup and produced by the Danish lighting manufacturer Focus during the 1960s. The lamps embody the clean lines and functional elegance characteristic of mid-century Scandinavian design. Each lamp features a polished brass half-dome, subtly convex in profile, with a refined and warm reflective surface that contributes to a soft ambient glow.",
  },
  {
    id: 53,
    name: "ERIK TIDSTRAND TABLE LAMP",
    category: "light",
    price: 2900,
    stock: 3,
    sku: "LGT-005",
    src: ["DSC_4094.jpg", "DSC_4091.jpg", "DSC_4093.jpg", "DSC_4100.jpg"],
    description:
      "This rare table lamp, designed by Erik Tidstrand and produced in the 1930s by Nordiska Kompaniet in Sweden, is a distinguished example of early Scandinavian modern design. Embodying a harmonious synthesis of function, material richness, and refined detailing, the lamp reflects both the transitional aesthetic of the interwar period and the enduring values of Swedish craftsmanship.",
  },
  {
    id: 54,
    name: "HANS-AGNE JAKOBSSON WALL LAMPS",
    category: "light",
    price: 4100,
    stock: 2,
    sku: "LGT-006",
    src: ["DSC_2212.jpg", "DSC_2211.jpg", "DSC_2215.jpg"],
    description:
      "The rare wall lamps, model V-180, designed by Hans-Agne Jakobsson and produced by Hans-Agne Jakobsson AB in Markaryd, Sweden, exemplify the designer’s talent for crafting lighting fixtures that merge sculptural form with atmospheric function. These pieces are a compelling representation of Scandinavian mid-century design, distinguished by their material richness, balanced proportions, and emphasis on indirect illumination.",
  },
]

export default Products
